### ISSUE TITLE
Using with Bitcore

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore-message#15]
The sign method is giving me "bitcore.ErrorInvalidArgument: Invalid Argument: First argument should be an instance of PrivateKey" although I created the private key with bitcore. I believe the problem is that the bitcore-message module uses a different bitcore module internally then the one I created the private key with.

**Comment by thofmann** [comment]
I was also having this problem.

I ended up "fixing" it by modifying my local bitcore-message module by changing the `sign` function to this:

```javascript
Message.prototype.sign = function sign(privateKey) {
  var privateKey = new PrivateKey(privateKey);
  var signature = this._sign(privateKey);
  return signature.toCompact().toString('base64');
};
```

Adding the `new PrivateKey` will cast it to a locally recognizable `PrivateKey`. This doesn't address the actual problem, but it does fix it.

**Comment by braydonf** [comment]
Updating the version required in bitcore-message to the same minor version of bitcore should fix this issue (fixed in https://github.com/bitpay/bitcore-message/pull/14 if you're using 0.11.x).

**Comment by olalonde** [comment]
For now, I just exposed bitcore in module.exports:

https://github.com/bitpay/bitcore-message/compare/master...olalonde:master

**Comment by maraoz** [comment]
should be good to go if you use latest npm versions of both modules (released today). Error messages were improved too. Let me know if the problem persists.
