### ISSUE TITLE
Can't verify testnet signature

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore-message#18]
I've been trying to verify the following testnet message/signature with bitcore-message, but keep getting this stack trace.

```
message: localhost:3000
address: mx5u3nqdPpzvEZ3vfnuUQEyHg3gHd8zrrH
signature: G4Bi9/Z7hF17MpE9t7Txm3n0aBH6yCVLFB1VWzkZRz17FxErgA/oOWmwXWYr6/ILlRCmeYjc8MeI8PQWYAElZY8=
```

```javascript
Invalid Argument: Error: i must be 0, 1, 2, or 3
Error
    at Error.NodeError (/src/node_modules/bitcore/lib/errors/index.js:20:41)
    at Object.module.exports.checkArgument (/src/node_modules/bitcore/lib/util/preconditions.js:14:13)
    at Function.Signature.fromCompact (/src/node_modules/bitcore/lib/crypto/signature.js:41:5)
    at Message.verify (/src/node_modules/bitcore-message/lib/message.js:92:29)
    at authenticate (/src/server/helpers/authenticate.js:38:32)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:82:5)
```

**Comment by smithb1994** [comment]
Can you post your code to see what you're doing wrong?
Judging by your error message, it could be a "bitcore" error, rather than a "bitcore-message" error.

**Comment by FoundationAwesome** [comment]
BUMP. got the same error. Ironically I came from bitcoinjs-lib where the documentation is also outdated.

**Comment by braydonf** [comment]
There is a known issue with uncompressed public keys that will produced the same error message: https://github.com/bitpay/bitcore-message/issues/12

**Comment by FoundationAwesome** [comment]
Took the key from here: https://brainwallet.org/#sign

5KYZdUEo39z3FPrtuX2QbbwGnNP5zTd7yyr2SC1j299sBCnWjss

**Comment by FoundationAwesome** [comment]
I can confirm that this bug does not happen with compressed keys. Wondering now how to workarround this bug.

**Comment by braydonf** [comment]
Adding support for uncompressed public keys in `Signature.fromCompact`: https://github.com/bitpay/bitcore/blob/master/lib/crypto/signature.js#L35 should fix the issue.

**Comment by FoundationAwesome** [comment]
![todo-bitcore](https://cloud.githubusercontent.com/assets/8321717/7789132/1491a53e-0256-11e5-844e-ef1a202a6cb9.png)
Maybe some expert in crypto-sigining wants to take on the todo? Would be really useful!

**Comment by smithb1994** [comment]
I've found that bitcoinjs-lib is much cleaner than bitcore's... Not sure why they don't have as many stars.

**Comment by braydonf** [comment]
Should be fixed in: https://github.com/bitpay/bitcore/pull/1250

**Comment by braydonf** [comment]
Should be fixed here with: https://github.com/bitpay/bitcore-message/pull/19
